name: Publish to GitHub Packages

on:
  workflow_dispatch:

env:
  PACKAGE_USERNAME: ${{ secrets.PACKAGE_USERNAME }}
  PACKAGE_REPO_TOKEN: ${{ secrets.PACKAGE_REPO_TOKEN }}
  PACKAGE_REPO: ${{ github.repository }}
  NEXUS_UPLOAD_REPOS_URL: ${{ vars.NEXUS_UPLOAD_REPOS_URL }}
  NEXUS_UPLOAD_REPOS_USER: ${{ vars.NEXUS_UPLOAD_REPOS_USER }}
  NEXUS_UPLOAD_REPOS_PWD: ${{ secrets.NEXUS_UPLOAD_REPOS_PWD }}
  AWS_OIDC_ROLE: ${{ secrets.AWS_OIDC_ROLE }}
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ env.AWS_OIDC_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle (including tests)
        run: ./gradlew build

      # Step 1: Publish commons module
      - name: Publish commons
        run: ./gradlew :commons:publish -x test --parallel -s -U -i

      # Step 2: Publish batch and online modules
      - name: Publish batch and online
        run: ./gradlew :common-batch:publish :common-online:publish -x test --parallel -s -U -i